/* uses sbt, which i installed with homebrew. */
/* this works without requiring the 'sbt plugin'. */

pipeline {
    agent any

    stages {

        stage('Compile') {
            steps {
                echo "Compiling..."
                sh "cd play-scala-forms-example && sbt sbtVersion"
            }
        }
 stage('Test') {
            steps {
                echo "Testing..."
                sh "cd play-scala-forms-example &&  sbt test"
            }
        }
        
        stage('Package') {
            steps {
                
                echo "Packaging..."
                sh "cd play-scala-forms-example && sbt rpm:packageBin"
            }
        }
         stage('Artifacts Upload') {
            steps {
        nexusArtifactUploader artifacts: [[artifactId: 'rpm-snapshot', classifier: '', file: 'play-scala-forms-example/target/rpm/RPMS/noarch/play-scala-forms-example-2.8.x-1.noarch.rpm', type: 'raw']], credentialsId: 'nexus-password', groupId: 'scala', nexusUrl: '172.31.47.241:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'rpm-snapshot', version: '1.0.0'
       }
        }
            }
             
}
