/* uses sbt, which i installed with homebrew. */
/* this works without requiring the 'sbt plugin'. */

pipeline {
    agent any

    stages {

        stage('Compile') {
            steps {
                echo "Compiling..."
                sh "cd play-scala-forms-example && sbt sbtVersion"
            }
        }
 stage('Test') {
            steps {
                echo "Testing..."
                sh "/usr/local/bin/sbt test"
            }
        }
        
        stage('Package') {
            steps {
                
                echo "Packaging..."
                sh "cd play-scala-forms-example && sbt rpm:packageBin"
            }
        }
    }
}
